### ISSUE TITLE
why show logout?

### ISSUE THREAD

**Issue by kaungkhant-thar** [MOPEAPAHLAING/Survey#1]
I think the problem is in Header component, you use this.props.auth but in App component you use Header component but not pass auth props.

**Comment by kaungkhant-thar** [comment]
Sorry don't see redux

**Comment by kaungkhant-thar** [comment]
![Screenshot from 2020-09-19 15-24-18](https://user-images.githubusercontent.com/49363818/93663243-519f9600-fa8c-11ea-9d80-61993aad0f23.png)
console.log(this.props.default) in default: block
and check it. Is there anything other than null and false?

**Comment by MOPEAPAHLAING** [comment]
I've solved the problem. Thank you.
