### ISSUE TITLE
google o auth error

### ISSUE THREAD

**Issue by kaungkhant-thar** [MOPEAPAHLAING/Survey#2]

**Comment by kaungkhant-thar** [comment]
![Screenshot from 2020-09-20 13-18-44](https://user-images.githubusercontent.com/49363818/93705492-e1544b80-fb43-11ea-8c15-4da96c978907.png)


Already log in async (access...) function?

**Comment by MOPEAPAHLAING** [comment]
Yes.

**Comment by kaungkhant-thar** [comment]
Email
